INSERT INTO traits (category, trait, description) VALUES
-- Colors
('color', 'blue', 'You are calm, thoughtful, and value deep connections.'),
('color', 'red', 'You are passionate, bold, and not afraid to stand out.'),
('color', 'green', 'You are balanced, growth-oriented, and value harmony.'),
('color', 'black', 'You are mysterious, independent, and highly self-aware.'),
('color', 'yellow', 'You are optimistic, energetic, and bring joy to others.'),

-- Animals
('animal', 'dog', 'You are loyal, friendly, and thrive in close relationships.'),
('animal', 'cat', 'You are independent, curious, and value personal freedom.'),
('animal', 'wolf', 'You are strategic, strong-willed, and value your inner circle.'),
('animal', 'owl', 'You are wise, observant, and think before acting.'),
('animal', 'lion', 'You are confident, courageous, and a natural leader.'),

-- Foods (optional, but fun)
('food', 'pizza', 'You are adaptable, social, and loved by almost everyone.'),
('food', 'sushi', 'You are refined, detail-oriented, and appreciate quality.'),
('food', 'burger', 'You are straightforward, reliable, and comforting to be around.'),
('food', 'salad', 'You are health-conscious, disciplined, and goal-driven.'),

('color', 'purple', 'You are creative, imaginative, and drawn to uniqueness.'),
('color', 'orange', 'You are energetic, enthusiastic, and socially confident.'),
('color', 'pink', 'You are compassionate, affectionate, and emotionally aware.'),
('color', 'white', 'You value simplicity, clarity, and fresh starts.'),
('color', 'gray', 'You are logical, reserved, and prefer balance over extremes.'),
('color', 'brown', 'You are grounded, dependable, and value stability.'),
('color', 'teal', 'You are calm under pressure and emotionally intelligent.'),
('color', 'cyan', 'You are innovative and enjoy thinking beyond conventions.'),
('color', 'gold', 'You are ambitious, confident, and driven by success.'),
('color', 'silver', 'You are modern, intuitive, and adaptable.'),
('color', 'maroon', 'You are intense, focused, and emotionally deep.'),
('color', 'navy', 'You are disciplined, trustworthy, and principled.'),
('color', 'lavender', 'You are gentle, empathetic, and spiritually inclined.'),
('color', 'beige', 'You are practical, calm, and prefer predictability.'),
('color', 'turquoise', 'You are expressive and thrive on communication.'),
('color', 'indigo', 'You are introspective and value inner wisdom.'),
('color', 'crimson', 'You are bold, determined, and emotionally intense.'),
('color', 'ivory', 'You are refined and appreciate subtle beauty.'),
('color', 'mint', 'You are refreshing, optimistic, and easygoing.'),
('color', 'peach', 'You are warm, friendly, and emotionally open.'),

-- More Animals (25)
('animal', 'fox', 'You are clever, adaptable, and quick-thinking.'),
('animal', 'bear', 'You are protective, strong, and value personal space.'),
('animal', 'eagle', 'You are visionary and strive for higher perspectives.'),
('animal', 'dolphin', 'You are playful, intelligent, and emotionally aware.'),
('animal', 'turtle', 'You are patient, thoughtful, and steady in progress.'),
('animal', 'rabbit', 'You are gentle, alert, and sensitive to surroundings.'),
('animal', 'horse', 'You value freedom, strength, and endurance.'),
('animal', 'snake', 'You are transformative and highly intuitive.'),
('animal', 'deer', 'You are kind-hearted and emotionally perceptive.'),
('animal', 'hawk', 'You are focused, decisive, and observant.'),
('animal', 'penguin', 'You are loyal and value long-term commitment.'),
('animal', 'koala', 'You are calm and prefer a peaceful lifestyle.'),
('animal', 'panda', 'You are gentle, approachable, and value harmony.'),
('animal', 'camel', 'You are resilient and can endure long challenges.'),
('animal', 'parrot', 'You are expressive and socially vibrant.'),
('animal', 'shark', 'You are determined and always moving toward goals.'),
('animal', 'frog', 'You are adaptable and comfortable with change.'),
('animal', 'swan', 'You are graceful and emotionally deep.'),
('animal', 'bat', 'You are perceptive and thrive in unconventional ways.'),
('animal', 'octopus', 'You are highly intelligent and flexible.'),
('animal', 'ant', 'You are disciplined and value teamwork.'),
('animal', 'bee', 'You are productive and community-focused.'),
('animal', 'peacock', 'You are expressive and confident in self-image.'),
('animal', 'owlbear', 'You combine wisdom with raw strength.'),
('animal', 'lizard', 'You are observant and emotionally resilient.'),

-- Foods (25)
('food', 'pasta', 'You are comforting and adaptable to many situations.'),
('food', 'ramen', 'You are thoughtful and appreciate depth and warmth.'),
('food', 'taco', 'You are lively and enjoy variety in life.'),
('food', 'steak', 'You are confident and value quality over quantity.'),
('food', 'icecream', 'You are joyful and nostalgic.'),
('food', 'chocolate', 'You are emotionally rich and deeply comforting.'),
('food', 'pancakes', 'You are warm-hearted and enjoy simple pleasures.'),
('food', 'friedrice', 'You are efficient and versatile.'),
('food', 'sandwich', 'You are reliable and straightforward.'),
('food', 'soup', 'You are nurturing and emotionally grounding.'),
('food', 'noodles', 'You are flexible and adaptable.'),
('food', 'curry', 'You are bold and complex.'),
('food', 'apple', 'You value health and consistency.'),
('food', 'banana', 'You are friendly and approachable.'),
('food', 'cheesecake', 'You enjoy indulgence with balance.'),
('food', 'dumplings', 'You value tradition and comfort.'),
('food', 'risotto', 'You are patient and detail-oriented.'),
('food', 'falafel', 'You are socially conscious and adventurous.'),
('food', 'omelette', 'You are adaptable and resourceful.'),
('food', 'smoothie', 'You are energetic and goal-focused.'),
('food', 'waffles', 'You are playful and optimistic.'),
('food', 'brownie', 'You are intense but comforting.'),
('food', 'granola', 'You are disciplined and health-minded.'),
('food', 'toast', 'You are dependable and simple.'),
('food', 'yogurt', 'You are balanced and mindful.'),

-- Hobbies (20)
('hobby', 'reading', 'You are introspective and value knowledge.'),
('hobby', 'gaming', 'You enjoy challenges and strategic thinking.'),
('hobby', 'traveling', 'You crave new experiences and perspectives.'),
('hobby', 'cooking', 'You enjoy creating comfort for others.'),
('hobby', 'writing', 'You are reflective and expressive.'),
('hobby', 'drawing', 'You are visually creative and observant.'),
('hobby', 'photography', 'You appreciate moments and details.'),
('hobby', 'coding', 'You are logical and enjoy problem-solving.'),
('hobby', 'gardening', 'You are patient and nurturing.'),
('hobby', 'hiking', 'You value clarity and solitude.'),
('hobby', 'music', 'You are emotionally expressive.'),
('hobby', 'singing', 'You are confident and emotionally open.'),
('hobby', 'dancing', 'You are energetic and expressive.'),
('hobby', 'yoga', 'You seek balance and inner peace.'),
('hobby', 'meditation', 'You are self-aware and grounded.'),
('hobby', 'chess', 'You are strategic and forward-thinking.'),
('hobby', 'sports', 'You are competitive and disciplined.'),
('hobby', 'baking', 'You enjoy precision and creativity.'),
('hobby', 'journaling', 'You value self-reflection.'),
('hobby', 'volunteering', 'You are empathetic and community-driven.');
